= About this Website
Christoph Tittel
2020-04-05
:page-layout: post
:toc:

In this post I want to talk about the story and technical details about this website.

// With this website I want to introduce myself and showcase some things I'm working on in my professional life.adfds

// == Intro
This is a static website hosted on https://pages.github.com/[GitHub Pages].

Previously it was based on Markdown files which were converted to HTML via https://pandoc.org/[Pandoc].
A Python script using https://jinja.palletsprojects.com/en/2.11.x/[jinja2] glued the pages together and different CSS files where responsible for the layout.

I recently switched to https://asciidoctor.org/[AsciiDoctor], another lightweight markup language like Markdown.
It combines the simplicity of Markdown with a much longer list of features included in the language specification.
AsciiDoc was originally developed as a simple way to write complex books in plaintext and is today used for this purpose by major publishers such as O'Reilly.

To construct a working website from those AsciiDoc-Files, the static site builder https://jekyllrb.com/[Jekyll] is used.
Jekyll natively supports only Markdown and HTML, but there is a plugin for AsciiDoc available.
Unfortunately this plugin is not whitelisted by GitHub-Pages footnote:[See https://pages.github.com/versions/].
To circumvent this problem, I set up a https://github.com/features/actions[GitHub action] to process my files from the incoming `source` branch of my repository with Jekyll (in this case all plugins are allowed) and move the 'compiled' HTML-files to the `main` branch which is served on the website.

Currently this website is using https://github.com/clayh53/tufte-jekyll[Tufte theme for Jekyll].
